#!/usr/bin/env python3
"""
BEATRIX CORS Exploitability Validator

This script helps verify if CORS findings are actually exploitable by:
1. Checking if the target uses cookie-based session auth
2. Testing if cross-origin requests can access authenticated data
3. Creating evidence for bug bounty reports

IMPORTANT: Only test on your own accounts!
"""

import subprocess


def check_cors_headers(url: str, origin: str = "https://evil.com") -> dict:
    """Check CORS headers on an endpoint"""
    result = subprocess.run(
        ["curl", "-s", "-I", "-H", f"Origin: {origin}", url],
        capture_output=True, text=True, timeout=10
    )

    headers = {}
    for line in result.stdout.split("\n"):
        if ":" in line:
            key, value = line.split(":", 1)
            headers[key.strip().lower()] = value.strip()

    return {
        "url": url,
        "origin_tested": origin,
        "acao": headers.get("access-control-allow-origin", ""),
        "acac": headers.get("access-control-allow-credentials", ""),
        "origin_reflected": origin in headers.get("access-control-allow-origin", ""),
        "credentials_allowed": headers.get("access-control-allow-credentials", "").lower() == "true",
    }


def analyze_exploitability(target: str, cors_result: dict) -> dict:
    """Analyze if a CORS finding is actually exploitable"""

    analysis = {
        "target": target,
        "cors_misconfigured": False,
        "exploitable": "unknown",
        "auth_method": "unknown",
        "severity": "none",
        "notes": [],
    }

    # Check if CORS is misconfigured
    if cors_result["origin_reflected"] and cors_result["credentials_allowed"]:
        analysis["cors_misconfigured"] = True
        analysis["notes"].append("CORS reflects origin with credentials=true")
    elif cors_result["origin_reflected"]:
        analysis["cors_misconfigured"] = True
        analysis["notes"].append("CORS reflects origin but no credentials")
        analysis["severity"] = "low"

    # Auth method hints
    auth_hints = {
        "stripe.com": ("api_key", "Stripe uses API keys, not cookies. CORS finding may be by design."),
        "discord.com": ("session_cookie", "Discord uses session cookies. Potentially exploitable!"),
        "spotify.com": ("session_cookie", "Spotify uses session cookies. Potentially exploitable!"),
        "atlassian.com": ("session_cookie", "Atlassian uses cookies. Potentially exploitable!"),
        "api.github.com": ("token", "GitHub API uses tokens, not cookies."),
    }

    for domain, (auth_type, note) in auth_hints.items():
        if domain in target:
            analysis["auth_method"] = auth_type
            analysis["notes"].append(note)

            if auth_type == "session_cookie" and analysis["cors_misconfigured"]:
                analysis["exploitable"] = "likely"
                analysis["severity"] = "high" if cors_result["credentials_allowed"] else "medium"
            elif auth_type in ["api_key", "token"]:
                analysis["exploitable"] = "unlikely"
                analysis["severity"] = "info"

    return analysis


def generate_evidence_report(findings: list) -> str:
    """Generate evidence report for bug bounty submission"""

    report = """# CORS Vulnerability Evidence Report
Generated by BEATRIX

## Summary
"""

    exploitable = [f for f in findings if f["analysis"]["exploitable"] == "likely"]
    info_only = [f for f in findings if f["analysis"]["exploitable"] == "unlikely"]

    report += f"""
- Total findings: {len(findings)}
- Likely exploitable: {len(exploitable)}
- Informational only: {len(info_only)}

## Exploitable Findings (Submit These)

"""

    for f in exploitable:
        report += f"""### {f['target']}

**CORS Headers:**
- Access-Control-Allow-Origin: `{f['cors']['acao']}`
- Access-Control-Allow-Credentials: `{f['cors']['acac']}`

**Exploitability:**
- Auth Method: {f['analysis']['auth_method']}
- Severity: {f['analysis']['severity'].upper()}

**Notes:**
"""
        for note in f['analysis']['notes']:
            report += f"- {note}\n"

        report += f"""
**cURL Evidence:**
```bash
curl -s -I -H "Origin: https://evil.com" "{f['target']}" | grep -i "access-control"
```

---

"""

    report += """## Informational Findings (Likely Not Exploitable)

"""
    for f in info_only:
        report += f"- **{f['target']}**: {', '.join(f['analysis']['notes'])}\n"

    return report


def main():
    targets = [
        "https://accounts.spotify.com/api/token",
        "https://discord.com/api/users/@me",
        "https://api.atlassian.com/me",
        "https://api.stripe.com/v1/account",
    ]

    print("=" * 60)
    print("BEATRIX CORS Exploitability Validator")
    print("=" * 60)

    findings = []

    for target in targets:
        print(f"\nAnalyzing: {target}")

        cors = check_cors_headers(target)
        analysis = analyze_exploitability(target, cors)

        findings.append({
            "target": target,
            "cors": cors,
            "analysis": analysis,
        })

        # Print summary
        status = "🔴 EXPLOITABLE" if analysis["exploitable"] == "likely" else "⚪ INFO ONLY"
        print(f"  {status}")
        for note in analysis["notes"]:
            print(f"    - {note}")

    # Generate report
    print("\n" + "=" * 60)
    report = generate_evidence_report(findings)

    # Save report
    with open("/home/usr/projects/bitwigcrack/bug_bounty_reports/EXPLOITABILITY_ANALYSIS.md", "w") as f:
        f.write(report)

    print("Report saved to: bug_bounty_reports/EXPLOITABILITY_ANALYSIS.md")

    # Summary
    exploitable = [f for f in findings if f["analysis"]["exploitable"] == "likely"]
    print(f"\n📊 Summary: {len(exploitable)}/{len(findings)} findings are likely exploitable")

    for f in exploitable:
        print(f"  ✅ {f['target']} - {f['analysis']['severity'].upper()}")


if __name__ == "__main__":
    main()
